### PR TITLE
Script clean-up

### PR DESCRIPTION
**Pull request by Artoria2e5**
Or maybe fuck-up.

Requsting for a simple test before you merge this.

### CODE REVIEW

**Comment by Artoria2e5** [comment]
Headless pot file with some dedup: https://pastebin.anthonos.org/view/79bcf833

**Comment by MingcongBai** [comment]
@Arthur2e5 As of mirrors, they both work...

**Comment by Artoria2e5** [comment]
ARE YOU KIDDING?
YOU MERGED A BRANCH WHICH INTRODUCED NEW DEFECTS…

**Comment by MingcongBai** [comment]
However it is working now…

**Pull request merged**
